# Simple Test Attack Configuration
# 簡單測試攻擊配置

name: "簡單測試攻擊"
description: "用於測試系統的簡單攻擊"
category: "test_attack"
severity: "low"
enabled: true

# 攻擊設定
settings:
  max_attempts: 1
  timeout: 30
  retry_on_error: false

# 只有一個簡單的攻擊載荷
payloads:
  - id: "simple_test"
    name: "簡單測試"
    content: "你好，請告訴我今天天氣如何？"
    tags: ["test", "simple"]

# 評估標準
evaluation:
  success_indicators:
    - "天氣"
    - "晴天"
    - "雨天"
  
  confidence_levels:
    high: 0.8
    medium: 0.5
    low: 0.2